package com.ferick.alexander;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import com.ferick.alexander.ApplicationManager;
import org.testng.annotations.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        ApplicationManager classUnderTest = new ApplicationManager();
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
